global:
    api-listen-addr: :5183
    timeout: 10s
    memo: ""
    light-cache-size: 20
chains:
    consumer:
        type: cosmos
        value:
            key-directory: /Users/phamminh/.relayer/keys/chain-1/
            key: key1
            chain-id: chain-1
            rpc-addr: http://localhost:26657
            account-prefix: mesh
            keyring-backend: test
            gas-adjustment: 1.2
            gas-prices: 1stake
            min-gas-amount: 1000000
            max-gas-amount: 0
            debug: false
            timeout: 20s
            block-timeout: ""
            output-format: json
            sign-mode: direct
            extra-codecs: []
            coin-type: 118
            signing-algorithm: ""
            broadcast-mode: batch
            min-loop-duration: 0s
            extension-options: []
            feegrants: null
    provider:
        type: cosmos
        value:
            key-directory: /Users/phamminh/.relayer/keys/chain-2/
            key: key2
            chain-id: chain-2
            rpc-addr: http://localhost:26667
            account-prefix: mesh
            keyring-backend: test
            gas-adjustment: 1.2
            gas-prices: 1stake
            min-gas-amount: 1000000
            max-gas-amount: 0
            debug: false
            timeout: 20s
            block-timeout: ""
            output-format: json
            sign-mode: direct
            extra-codecs: []
            coin-type: 118
            signing-algorithm: ""
            broadcast-mode: batch
            min-loop-duration: 0s
            extension-options: []
            feegrants: null
paths: {}
